databases:
  - name: pharmly-postgres
    databaseName: pharmly
    user: pharmly_user
    plan: free
    region: oregon

services:
  - type: web
    name: pharmly-pms
    env: node
    plan: free
    region: oregon
    buildCommand: cd backend && npm install --include=dev && npm run build
    startCommand: cd backend && node dist/database/seed.js && npm run start:prod
    healthCheckPath: /api/v1/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.18.0
      - key: PORT
        value: 10000
      - key: API_PREFIX
        value: api/v1
      - key: DATABASE_URL
        fromDatabase:
          name: pharmly-postgres
          property: connectionString
      - key: DB_TYPE
        value: postgres
      - key: DB_SYNCHRONIZE
        value: true
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 8h
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: BCRYPT_SALT_ROUNDS
        value: 10
      - key: CORS_ORIGINS
        value: https://pharmly-pms.onrender.com,http://localhost:3000,http://localhost:5500
